/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.xtext.example.mydsl.idea.lang.MyDslLanguage;

public class MyDslFacetType extends AbstractFacetType<MyDslFacetConfiguration> {

	public static final FacetTypeId<Facet<MyDslFacetConfiguration>> TYPEID = new FacetTypeId<Facet<MyDslFacetConfiguration>>("org.xtext.example.mydsl.MyDsl");

	public MyDslFacetType() {
		super(TYPEID, "org.xtext.example.mydsl.MyDsl", "MyDsl");
		MyDslLanguage.INSTANCE.injectMembers(this);
	}
}
