/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class MyDslLanguage extends AbstractXtextLanguage {

	public static final MyDslLanguage INSTANCE = new MyDslLanguage();

	private MyDslLanguage() {
		super("org.xtext.example.mydsl.MyDsl");
	}

}
