/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.lang;

import org.xtext.example.mydsl.idea.lang.AbstractMyDslFileType;

@SuppressWarnings("all")
public class MyDslFileType extends AbstractMyDslFileType {
  public final static MyDslFileType INSTANCE = new MyDslFileType();
  
  public MyDslFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(MyDslLanguage) is undefined");
  }
}
