/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;
import org.xtext.example.mydsl.idea.lang.MyDslLanguage;

public class MyDslSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return MyDslLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
