/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.highlighting;

import org.xtext.example.mydsl.idea.highlighting.MyDslBaseColorSettingsPage;

@SuppressWarnings("all")
public class MyDslColorSettingsPage extends MyDslBaseColorSettingsPage {
}
