/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea;

import com.google.inject.Injector;
import org.xtext.example.mydsl.MyDslStandaloneSetupGenerated;

@SuppressWarnings("all")
public class MyDslStandaloneSetupIdea extends MyDslStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from MyDslIdeaModule to Module");
  }
}
