/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.idea.completion;

import org.xtext.example.mydsl.idea.completion.AbstractMyDslCompletionContributor;
import org.xtext.example.mydsl.idea.lang.MyDslLanguage;

@SuppressWarnings("all")
public class MyDslCompletionContributor extends AbstractMyDslCompletionContributor {
  public MyDslCompletionContributor() {
    this(MyDslLanguage.INSTANCE);
  }
  
  public MyDslCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
